/* Insert Cart Details */
INSERT INTO ORDER_DETAILS VALUES (1, 1, 'Y', 1, NOW(), 1, NOW(), 0);
INSERT INTO ORDER_DETAILS VALUES (2, 1, 'Y', 2, NOW(), 2, NOW(), 0);

INSERT INTO ORDER_DETAILS VALUES (3, 2, 'Y', 1, NOW(), 1, NOW(), 0);
INSERT INTO ORDER_DETAILS VALUES (4, 2, 'Y', 2, NOW(), 2, NOW(), 0);

/* Insert Cart Product Details */
INSERT INTO ORDER_PRODUCT_MAPPING VALUES (1, 1, 1, 1, 'Y', 1, NOW(), 1, NOW(), 0);
INSERT INTO ORDER_PRODUCT_MAPPING VALUES (2, 1, 4, 1, 'Y', 1, NOW(), 1, NOW(), 0);
INSERT INTO ORDER_PRODUCT_MAPPING VALUES (3, 1, 2, 2, 'Y', 1, NOW(), 1, NOW(), 0);

INSERT INTO ORDER_PRODUCT_MAPPING VALUES (4, 2, 9, 4, 'Y', 1, NOW(), 1, NOW(), 0);