DROP TABLE IF EXISTS ORDER_DETAILS;
CREATE TABLE ORDER_DETAILS(
	ORDER_ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT(10) NOT NULL,
	ORDER_DATE TIMESTAMP,
	TOTAL_PRICE DECIMAL(10,2) NOT NULL,
	IS_ACTIVE CHAR NOT NULL,
	CREATED_BY INT(10) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_BY INT(10),
	LAST_MODIFIED_DATE TIMESTAMP,
	VERSION INT(10) NOT NULL
);

DROP TABLE IF EXISTS ORDER_PRODUCT_MAPPING;
CREATE TABLE ORDER_PRODUCT_MAPPING(
	ORDER_PRODUCT_ID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ORDER_ID INT(10) NOT NULL,
	PRODUCT_ID INT(10) NOT NULL,
	PRODUCT_COUNT INT(10) NOT NULL,
	IS_ACTIVE CHAR NOT NULL,
	CREATED_BY INT(10) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_BY INT(10),
	LAST_MODIFIED_DATE TIMESTAMP,
	VERSION INT(10) NOT NULL
);